"""stage-signal public API."""

from .constants import (
    DEFAULT_STALE_THRESHOLD,
    DOCTOR_JSON_KEYS,
    EVENT_TYPES,
    EXIT_BAD_ARGS,
    EXIT_BLOCKED,
    EXIT_CODES,
    EXIT_ERROR,
    EXIT_FAILED,
    EXIT_ILLEGAL_TRANSITION,
    EXIT_NOT_INITIALIZED,
    EXIT_OK,
    EXIT_QUEUED,
    EXIT_RUNNING,
    EXIT_WAIT_TIMEOUT,
    SCHEMA_VERSION,
    STATES,
    STATUS_JSON_KEYS,
    STATUS_REQUIRED_KEYS,
    SUPERVISE_DEFAULT_EVERY,
    TERMINAL_STATES,
    WAIT_JSON_KEYS,
    WARNING_CODE_DEAD_PID,
    WARNING_CODE_STALE_HEARTBEAT,
    WARNING_CODE_UNPARSEABLE_HEARTBEAT,
    state_exit_code,
)
from .errors import (
    BadArgsError,
    CorruptStatusError,
    IllegalTransition,
    NotInitialized,
    StageError,
    WaitTimeout,
)
from .stage import (
    Stage,
    verify_proof,
    wait_condition_met,
    want_matches,
    write_status_mirror,
)
from .store import StageStore, resolve_dir

__version__ = "0.1.6"

__all__ = [
    "__version__",
    "Stage",
    "StageError",
    "BadArgsError",
    "CorruptStatusError",
    "IllegalTransition",
    "NotInitialized",
    "WaitTimeout",
    "StageStore",
    "resolve_dir",
    "state_exit_code",
    "verify_proof",
    "wait_condition_met",
    "want_matches",
    "write_status_mirror",
    "SCHEMA_VERSION",
    "STATES",
    "TERMINAL_STATES",
    "DEFAULT_STALE_THRESHOLD",
    "SUPERVISE_DEFAULT_EVERY",
    "WARNING_CODE_DEAD_PID",
    "WARNING_CODE_STALE_HEARTBEAT",
    "WARNING_CODE_UNPARSEABLE_HEARTBEAT",
    "EVENT_TYPES",
    "EXIT_CODES",
    "EXIT_OK",
    "EXIT_ERROR",
    "EXIT_BAD_ARGS",
    "EXIT_ILLEGAL_TRANSITION",
    "EXIT_RUNNING",
    "EXIT_BLOCKED",
    "EXIT_FAILED",
    "EXIT_QUEUED",
    "EXIT_WAIT_TIMEOUT",
    "EXIT_NOT_INITIALIZED",
    "STATUS_REQUIRED_KEYS",
    "STATUS_JSON_KEYS",
    "DOCTOR_JSON_KEYS",
    "WAIT_JSON_KEYS",
]
